version: '3.8'

services:
  isso:
    image: machines/isso
    container_name: isso
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./config:/config
      - ./db:/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - ISSO_SMTP_PASSWORD=${ISSO_SMTP_PASSWORD}
      - ISSO_ADMIN_PASSWORD=${ISSO_ADMIN_PASSWORD}
    ports:
      - "8080:8080"

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: tunnel
    restart: always
    command: tunnel run --token eyJhIjoiMjJiYTUyNjFlZTc0NzAzMzU3ZGFmZjRmMTAxZTdhOGQiLCJ0IjoiMzU2YTkzMzQtOWRjOC00YWE0LWFjZDEtZjE0YWIyMGFmOGFjIiwicyI6IlptWXpZekU0WXpRdFlqSmtNaTAwT1daaExXSTRNMll0TWpOaE1EQTVZbUUyWXpBeSJ9
