version: '3'

services:
  isso:
    image: machines/isso
    container_name: isso
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - UID=1000
      - GID=1000
      - ISSO_SMTP_PASSWORD=${SMTP_PASSWORD}
      - ISSO_ADMIN_PASSWORD=${ISSO_ADMIN_PASSWORD}
    volumes:
      - ./config:/config
      - ./db:/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8080:8080"
    networks:
      - isso-net

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: tunnel
    restart: always
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    networks:
      - isso-net

networks:
  isso-net:
    driver: bridge
