[general]
dbpath = /db/comments.db
host = https://architect.adiendendra.com/
notify = smtp
max-age = 0
reply-to-self = true

[smtp]
host = smtp.gmail.com
port = 587
security = starttls
timeout = 10
username = adien.dendra@gmail.com
password = ${ISSO_SMTP_PASSWORD}
from = "Isso Comments" <adien.dendra@gmail.com>
to = hello@adiendendra.com

[server]
listen = http://0.0.0.0:8080
public-endpoint = https://issocomment.adiendendra.com
ssl = false  # Ubah jadi false, biarkan SSL diurus oleh Cloudflare/Proxy

[moderation]
enabled = true

[admin]
enabled = true
password = $ISSO_ADMIN_PASSWORD

[guard]
enabled = true
require-author = false
require-email = false
